version: "3.5"
services:
  beacon-chain:
    image: "beacon-chain.prysm-ropsten-websigner.dnp.dappnode.eth:1.0.0"
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v2.1.2
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - "13303:13303/tcp"
      - "12303:12303/udp"
    restart: unless-stopped
    environment:
      HTTP_WEB3PROVIDER: "http://ropsten.dappnode:8551"
      CHECKPOINT_SYNC_URL: ""
      CORSDOMAIN: "http://prysm-ropsten.dappnode"
      TTD_OVERRIDE: 50000000000000000
      WEB3_BACKUP: ""
      P2P_TCP_PORT: 13303
      P2P_UDP_PORT: 12303
      EXTRA_OPTS: ""
  validator:
    image: "validator.prysm-ropsten-websigner.dnp.dappnode.eth:1.0.0"
    build:
      context: validator
      dockerfile: Dockerfile
      args:
        UPSTREAM_VERSION: v2.1.2
        BRANCH: develop
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      LOG_TYPE: INFO
      BEACON_RPC_PROVIDER: "beacon-chain.prysm-ropsten.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-ropsten.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
volumes:
  beacon-chain-data: {}
  validator-data: {}
